function mainLoop() {
  ctx.save()
  ctx.translate(-MainCamera.pos.x, -MainCamera.pos.y)
  ctx.drawImage(sprites.background, 0, 0)
  cameraMoves()
  startForest()
  drawEveryObstacle()
  enemyFunctions()
  laserUpdate()
  heroFunctions()
  ctx.drawImage(sprites.shadowsbg, 0, 0)
  ctx.restore()
  joystick.draw()
  mobileButtons.draw()
  requestAnimationFrame(mainLoop)
}
